name: "make docker image"

on:
  push:
    branches: ["release"]

env:
  IMAGE_NAME: wechat-work-resource

jobs:
  build_and_push_image:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositioin
        uses: actions/checkout@v2
      
      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aug0cz/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
